# Generated by Django 4.1.2 on 2022-11-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_profilemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='posts/blog_img'),
        ),
    ]
